### ISSUE TITLE
paginate on raw knex?

### ISSUE THREAD

**Issue by ahsandev2019** [felixmosh/knex-paginate#13]
any feature to enable pagination in knex.raw() ? 
i have tried use 
```
knex
.raw(`select * from data`).
.paginate({ perPage: 10, currentPage:  1 })

```
but i get eror like this 

`{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "knex.raw(...).paginate is not a function"
}`

**Comment by felixmosh** [comment]
Hi, thank you for reporting this issue 🙏🏼 

Pagination extends the queryBuilder object, probably `raw` is not part of it...

Can u try to run 
`knex.raw(`select * from data`).limit(1)`
If this works I will investigate why pagination not works.

**Comment by felixmosh** [comment]
Hi, thank you for reporting this issue 🙏🏼 

Pagination extends the queryBuilder object, probably `raw` is not part of it...

Can u try to run 
`knex.raw(`select * from data`).limit(1)`
If this works I will investigate why pagination not works.

**Comment by ahsandev2019** [comment]
thanks for response 
i have some complicated query like this 

`SELECT karyawan.nip, profil.nik, profil.nama,DATE(tgl_masuk) AS tanggalmasuk, DATE(tgl_aktif)as tgl_resmi,desa.desa, kecamatan, kabupaten, provinsi.nama_provinsi, kodepos, COALESCE(profil.upload_image ,'') AS foto,
        jabatan.id, jabatan.nama_jabatan,tipe_gaji,sistem_penggajian, unit_kerja.kode,  profil.jenis_kelamin, profil.status_perkawinan, profil.alamat, profil.pendidikan,
        CONCAT(TIMESTAMPDIFF(YEAR,karyawan.tgl_masuk,NOW()),'th',',',TIMESTAMPDIFF(MONTH,karyawan.tgl_masuk,NOW())% 12,'bln',',',FLOOR(TIMESTAMPDIFF(DAY, tgl_masuk, NOW()) % 30.4375),'hr') AS lamakerja, LEAST(CEILING(TIMESTAMPDIFF(YEAR,karyawan.tgl_masuk,NOW()) /periode_grade),max_grade) AS grade,
        COALESCE((SELECT nama FROM unit_kerja WHERE kode = left(karyawan.kode_unit_kerja,3) and LENGTH(kode)=3 LIMIT 1),'') AS Departemen,
        COALESCE((SELECT nama FROM unit_kerja WHERE kode = left(karyawan.kode_unit_kerja,7) and LENGTH(kode)=7 LIMIT 7),'') AS Unit,
        COALESCE((SELECT nama FROM unit_kerja WHERE kode = left(karyawan.kode_unit_kerja,11) and LENGTH(kode)=11 LIMIT 11),'') AS grup,
        COALESCE((SELECT status_jabatan.nama FROM status_jabatan WHERE status_jabatan.id = mutasi_jabatan.id_status_jabatan),'') AS statusjabatan,
        COALESCE((SELECT status_jabatan.id FROM status_jabatan WHERE status_jabatan.id = mutasi_jabatan.id_status_jabatan),'') AS idstatusjabatan
        FROM karyawan, mutasi_jabatan, profil,jabatan,unit_kerja,desa, provinsi
        WHERE karyawan.nip=mutasi_jabatan.nip
        AND profil.id=karyawan.id_profil
        AND jabatan.id = mutasi_jabatan.id_jabatan
        AND unit_kerja.kode =mutasi_jabatan.kode_unit_kerja
        AND mutasi_jabatan.status_mutasi='Active'
        AND desa.kode_provinsi = provinsi.kode_provinsi
        AND desa.id_desa=profil.id
        AND karyawan.status='Aktif'
        ORDER BY mutasi_jabatan.created_at DESC`

and its really pain to implementation in knex, any solution to use paginate in knex.raw?

**Comment by ahsandev2019** [comment]
solved with some sub-query method

`let result = await knex("karyawan as k")
      .join("profil as p", "p.id", "k.id_profil")
      .join("mutasi_jabatan  as mj", "mj.nip", "k.nip")
      .join("jabatan  as j", "j.id", "mj.id_jabatan")
      .join("unit_kerja  as uk", "uk.kode", "mj.kode_unit_kerja")
      .join("desa as d", "d.id_desa", "p.id")
      .join("provinsi as p2", "p2.kode_provinsi", "d.kode_provinsi")
      .distinct("k.nip")
      .select(
        "p.nik",
        "p.nama",
        "d.desa",
        "kecamatan",
        "kabupaten",
        "p2.nama_provinsi",
        "kodepos",
        "j.id",
        "j.nama_jabatan",
        "tipe_gaji",
        "sistem_penggajian",
        "uk.kode",
        "p.jenis_kelamin",
        "p.status_perkawinan",
        "p.alamat",
        "p.pendidikan",
        knex.raw(
          "CONCAT(TIMESTAMPDIFF(YEAR,k.tgl_masuk,NOW()),'th',',',TIMESTAMPDIFF(MONTH,k.tgl_masuk,NOW())% 12,'bln',',',FLOOR(TIMESTAMPDIFF(DAY, tgl_masuk, NOW()) % 30.4375),'hr') AS lamakerja, LEAST(CEILING(TIMESTAMPDIFF(YEAR,k.tgl_masuk,NOW()) /periode_grade),max_grade) AS grade"
        ),
        knex.raw(
          "COALESCE((SELECT nama FROM unit_kerja WHERE kode = left(k.kode_unit_kerja,3) and LENGTH(kode)=3 LIMIT 1),'') AS Departemen"
        ),
        knex.raw(
          "COALESCE((SELECT nama FROM unit_kerja WHERE kode = left(k.kode_unit_kerja,7) and LENGTH(kode)=7 LIMIT 7),'') AS Unit"
        ),
        knex.raw(
          "COALESCE((SELECT nama FROM unit_kerja WHERE kode = left(k.kode_unit_kerja,11) and LENGTH(kode)=11 LIMIT 11),'') AS grup"
        ),
        knex.raw(
          "COALESCE((SELECT status_jabatan.nama FROM status_jabatan WHERE status_jabatan.id = mj.id_status_jabatan),'') AS statusjabatan"
        ),
        knex.raw(
          "COALESCE((SELECT status_jabatan.id FROM status_jabatan WHERE status_jabatan.id = mj.id_status_jabatan),'') AS idstatusjabatan"
        ),
        knex.raw("DATE(tgl_masuk) AS tanggalmasuk"),
        knex.raw("DATE(tgl_aktif)as tgl_resmi"),
        knex.raw("COALESCE(p.upload_image ,'') AS foto")
      )
      .paginate({ perPage: 20, currentPage: data || 1 });

    return result;`

thanks for paginate feature, its make me faster in writing code

**Comment by robsonkades** [comment]
this feature would help me a lot

**Comment by felixmosh** [comment]
> this feature would help me a lot

As I've explained, `raw` is not part of the querybuilder object.
Maybe you can do something like, 
```js
knex.select(knex.raw('your-raw-query')).paginate()
```
