### ISSUE TITLE
Support underscore?

### ISSUE THREAD

**Issue by Zyles** [felixmosh/knex-paginate#17]
Does this library support underscores to be more consistent with the rest of our API?

**Comment by felixmosh** [comment]
Can you elaborate? what do you mean by underscore?

**Comment by felixmosh** [comment]
Ping?

**Comment by Zyles** [comment]
I'm returning result to my API:

```
"pagination": {
        "total": 4,
        "lastPage": 1,
        "perPage": 10,
        "currentPage": 1,
        "from": 0,
        "to": 4
    }
```

Would like underscore as last_page, per_page, current_page.

But maybe I should transform the DB response instead?

**Comment by felixmosh** [comment]
Ha, i got it...
I will check if it is possible to do

**Comment by felixmosh** [comment]
`v2.2.0` has added a call to [postProcessResponse](http://knexjs.org/#Installation-post-process-response) on the pagination object, so you can specify your required string case.

If you are not using [`knex-stringcase`](https://github.com/Kequc/knex-stringcase) check it out.
