### ISSUE TITLE
Must use paginate last or it breaks

### ISSUE THREAD

**Issue by ghostdevv** [felixmosh/knex-paginate#18]
Whenever I try to run a query after paginate has been called it fails, for example:

```js
const query = db('users')
    .select('id', 'username')
    .orderBy('username')
    .paginate({})
    .where({ admin: false });
```

Results in the following error:

```
UnhandledPromiseRejectionWarning: TypeError: db(...).select(...).orderBy(...).paginate(...).where is not a function
```

**Comment by felixmosh** [comment]
This is by design, since internally `paginate` splits the given query into 2 queries. (one for counting total rows and one for the paginated result).
