### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by coolballal** [felixmosh/knex-paginate#26]
The paginate functionality works as expected when the application is run locally. But, when the paginate function is executed within docker container it throws a SEGFAULT exception. What could be the reason for this?

**Comment by felixmosh** [comment]
Hi, thank you for reporting this issue.
What is the error? Segfault is an error that I've know from C :)

**Comment by coolballal** [comment]
The container crashes with status as Exited (139) 1 second ago.

**Comment by coolballal** [comment]
I'm using node:16-alphine image and Oracle instantclient installed on it.

**Comment by felixmosh** [comment]
Hi, I don't think that it is related to this lib.
There is no chance that node code will crush the docker container.

**Comment by coolballal** [comment]
It's possible that it's related to something else. The only reason why I thought it could be related is because without having paginate on the query the results are returned as expected. As soon as I add paginate to the query it crashes the container. The same code works fine when it is executed outside the container.

**Comment by felixmosh** [comment]
Maybe it is a memory issue... or some other docker config

**Comment by coolballal** [comment]
Have you tried this in node:18-alpine image?

**Comment by felixmosh** [comment]
No, I'm not using docker at prod

**Comment by coolballal** [comment]
I have uninstalled knex-paginate and even after that when I add offset or limit to my query it crashes the docker container. It seems to be issue with knex library.

**Comment by felixmosh** [comment]
closing, since it is not related to this lib.
Feel free to reopen if you thing otherwise
