### ISSUE TITLE
'total' and 'lastPage' properties returning the NaN value.

### ISSUE THREAD

**Issue by ThiagoMB60** [felixmosh/knex-paginate#27]
Good morning, I'm having a problem when my search returns 0 results. This generates fake pages when using 'datatables', anyway I solved it by handling this on the frontend. But I believe that the ideal would be to return the value 0 when no record is found. I immediately apologize if I made a mistake in using this tool.

output example obtained:
```ts
{
  data: [],
  pagination: {
    total: NaN,
    lastPage: NaN,
    perPage: '50',
    currentPage: '1',
    from: 0,
    to: 0
  }
}
```

**Comment by felixmosh** [comment]
Can you share how did you call the lib? what parameters did you passed? what values it returned to you?

**Comment by felixmosh** [comment]
Can you add the .debug(true) before .paginate to show you 2 queries that runs, paste them here pls.

**Comment by ThiagoMB60** [comment]
> Can you add the .debug(true) before .paginate to show you 2 queries that runs, paste them here pls.

The following are queries:

```
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 50 ],
  __knexQueryUid: 'HiJKmcRK9IE2XrfdqcnLj',
  sql: "select first ?  c000025.CODIGO, PRODUTO, PRECOVENDA, FOTO, QTDE_EMBALAGEM, REFERENCIA, CODBARRA, UNIDADE, c000100.ESTOQUE_ATUAL, c000019.NOME from c000025 left join c000100 on c000100.CODPRODUTO = c000025.CODIGO left join c000019 on c000019.CODIGO = c000025.CODMARCA where PRODUTO CONTAINING 'IDHSJXBE' order by PRODUTO asc"
}
{
  method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: '9rucjHUeMJIu1ZZEZaGYW',
  sql: "select first ?  count(*) as total from (select   c000025.CODIGO, PRODUTO, PRECOVENDA, FOTO, QTDE_EMBALAGEM, REFERENCIA, CODBARRA, UNIDADE, c000100.ESTOQUE_ATUAL, c000019.NOME from c000025 left join c000100 on c000100.CODPRODUTO = c000025.CODIGO left join c000019 on c000019.CODIGO = c000025.CODMARCA where PRODUTO CONTAINING 'IDHSJXBE') as count__query__"
}
```

**Comment by felixmosh** [comment]
Where this `Select first` comes from?

**Comment by ThiagoMB60** [comment]
> Where this `Select first` comes from?

I believe it is added by knex-paginate itself, as at no time did I define it. If I run the dem statement the '.paginate({})', the 'select first' is not added. Be yourself:

`
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ '000200' ],
  __knexQueryUid: 'UJHGWog3qlVuuXMrRyYU1',
  sql: 'select   c000025.CODIGO, PRODUTO, PRECOVENDA, FOTO, QTDE_EMBALAGEM, REFERENCIA, CODBARRA, UNIDADE, c000100.ESTOQUE_ATUAL, c000019.NOME from
c000025 left join c000100 on c000100.CODPRODUTO = c000025.CODIGO left join c000019 on c000019.CODIGO = c000025.CODMARCA where C000025.CODIGO = ? order by PRODUTO asc'
}
`

**Comment by ThiagoMB60** [comment]
For the sake of simplicity, I removed the relationships and ordering from the query. See that the problem still persists. there is no record in table 'C000025' with property 'CODIGO' with value = '006487' as I am trying to find:

```
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 50, '006487' ],
  __knexQueryUid: 'RjC2eJTZs1INxZuj5HiBc',
  sql: 'select first ?  * from c000025 where C000025.CODIGO = ?'
}
{
  method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, '006487' ],
  __knexQueryUid: 'ZMapzBE_KjK3pY71m5V5e',
  sql: 'select first ?  count(*) as total from (select   * from c000025 where C000025.CODIGO = ?) as count__query__'
}

//result ↓↓↓
{
  data: [],
  pagination: {
    total: NaN,
    lastPage: NaN,
    perPage: '50',
    currentPage: '1',
    from: 0,
    to: 0
  }
}
```

**Comment by felixmosh** [comment]
What DB do you use?

**Comment by ThiagoMB60** [comment]
> What DB do you use?

Firebird, and I'm using the "knex-firebird-dialect": "^1.4.2".

**Comment by felixmosh** [comment]
> > What DB do you use?
> 
> Firebird, and I'm using the "knex-firebird-dialect": "^1.4.2".

Ha, OK, I'm not familiar with this dialect, but it looks OK (probably).

**Comment by ThiagoMB60** [comment]
> ```ts
> select first 1  count(*) as total from (select   * from c000025 where C000025.CODIGO = '006487'
> ```

I runned it o IBExpert and it returned me a valid query with the count indicating 0:
`select first 1 count(*) as total from (select   * from c000025 where C000025.CODIGO = '006487')`

result ↓
![image](https://user-images.githubusercontent.com/50173175/199072266-38ee9b33-0834-496d-9e0e-2f951da1da44.png)

**Comment by ThiagoMB60** [comment]
> What DB do you use?
> 
> Can you check what your DB returns when you query something like this?
> 
> ```ts
> await database.raw(`select first 1  count(*) as total from (select   * from c000025 where C000025.CODIGO = '006487') as count__query__`)
> ```

And I also tried using knex as suggested and this was the result

`[ { TOTAL: 0 } ]`

**Comment by felixmosh** [comment]
OK, what will be returned in a query that should return values?

**Comment by ThiagoMB60** [comment]
> OK, what will be returned in a query that should return values? Looks like instead of returning the first element (as it should) in the array, it returns the array it self... :| Weird.

Queries with .debug:

```
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 50 ],
  __knexQueryUid: 'WWKZWPMeD9jhlzZNUROT0',
  sql: 'select first ?  c000025.CODIGO, PRODUTO, PRECOVENDA, FOTO, QTDE_EMBALAGEM, REFERENCIA, CODBARRA, UNIDADE, c000100.ESTOQUE_ATUAL, c000019.NOME from c000025 left join c000100 on c000100.CODPRODUTO = c000025.CODIGO left join c000019 on c000019.CODIGO = c000025.CODMARCA order by PRODUTO asc'

}
{
  method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: '8IRmwj-4oZNQNDXtS8o7f',
  sql: 'select first ?  count(*) as total from (select   c000025.CODIGO, PRODUTO, PRECOVENDA, FOTO, QTDE_EMBALAGEM, REFERENCIA, CODBARRA, UNIDADE, c000100.ESTOQUE_ATUAL, c000019.NOME from c000025 left join c000100 on c000100.CODPRODUTO = c000025.CODIGO left join c000019 on c000019.CODIGO = c000025.CODMARCA) as count__query__'
}
```

result ↓↓↓

```
{
  data: [{  
     //50 first objects found inside this array (:P)
  }],
  pagination: {
    total: 4064,
    lastPage: 82,
    perPage: '50',
    currentPage: '1',
    from: 0,
    to: 50
  }
}
```

**Comment by felixmosh** [comment]
Can you run this 
```ts
await database.raw(`select first 1  count(*) as total from (select   c000025.CODIGO, PRODUTO, PRECOVENDA, FOTO, QTDE_EMBALAGEM, REFERENCIA, CODBARRA, UNIDADE, c000100.ESTOQUE_ATUAL, c000019.NOME from c000025 left join c000100 on c000100.CODPRODUTO = c000025.CODIGO left join c000019 on c000019.CODIGO = c000025.CODMARCA) as count__query__`);
```

**Comment by ThiagoMB60** [comment]
> ```ts
> select first 1  count(*) as total from (select   c000025.CODIGO, PRODUTO, PRECOVENDA, FOTO, QTDE_EMBALAGEM, REFERENCIA, CODBARRA, UNIDADE, c000100.ESTOQUE_ATUAL, c000019.NOME from c000025 left join c000100 on c000100.CODPRODUTO = c000025.CODIGO left join c000019 on c000019.CODIGO = c000025.CODMARCA) as count__query__
> ```

Working fine: 
![image](https://user-images.githubusercontent.com/50173175/199087533-4c6a8d58-0f36-4d9a-b41b-075a7ba5a80a.png)

**Comment by felixmosh** [comment]
What is the object that it returns? :]

**Comment by felixmosh** [comment]
So, in this case it not returns it as `[ { TOTAL: 4064 } ]`

**Comment by ThiagoMB60** [comment]
> So, in this case it not returns it as `[ { TOTAL: 4064 } ]`?

Sorry, I performed the query by IBExpert, but by knex yes, this is exactly the result

**Comment by felixmosh** [comment]
It doesn't make sense, the code assumes that it gets the total value as a clear value (this is what `.first()` does in all the dbs)...
Can you check this?

**Comment by felixmosh** [comment]
Ham, sorry, my test is not right 😅
Can you open node_modules and add a print of the count result?

Do you have discord, so we will be able to chat?

**Comment by ThiagoMB60** [comment]
> Ham, sorry, my test is not right sweat_smile Can you open node_modules and add a print of the count result?
> 
> Do you have discord, so we will be able to chat?

Sure,  ThiagoMB#1230
