### ISSUE TITLE
How to paginate many to one relations?

### ISSUE THREAD

**Issue by JCMais** [felixmosh/knex-paginate#3]
Say for instance that I'm building an endpoint to list users from a table, and each user can have multiple roles. This sounds as simples as:
```sql
SELECT u.*, r."role" FROM users as u LEFT JOIN roles as r ON r.uid = u.id
```

However if I use this library to paginate that query, it will look like this:
```sql
SELECT u.*, r."role" FROM users as u LEFT JOIN roles as r ON r.uid = u.id LIMIT 10 OFFSET 0
```

Which is semantically correct, but not quite right for my use case. With SQL one way to fix this is by having the query like the following:
```sql
SELECT u.*, r."role" FROM (SELECT u.* FROM users as u [WHERE CLAUSE] LIMIT 10 OFFSET 0) as u LEFT JOIN roles as r ON r.uid = u.id
```

Is there any way to do something similar using this library?

**Comment by felixmosh** [comment]
Hi, thanks for opening the issue.. I'm not sure i got what are you trying to achieve.

What do u want to paginate? Users or roles?

**Comment by JCMais** [comment]
Users, but still retrieve all roles to the paginated users.

From what I can see the way this library works it currently does not allow to paginate queries with 1-to-n relationships, only 1-to-1.

For example, let's say I have 10 users and each users has 2 roles, and then I write the following query with knex to retrieve all data on this relation:
```
knex('users as u').select('u.*', 'r.*').leftJoin('roles as r', 'r.uid', 'u.id')
```

If I try to paginate that with this library, using perPage = 5 and page = 0, it's going to return only the first 3 users, the first two with all their roles, and the third one with just their first role.

This is because those would make 5 rows:
| id | username | role  | uid  |
|---|---|---|---|
|  1 | user-a | moderator  | 1  |
|  1 | user-a | chat-admin | 1  |
|  2 | user-b | moderator  | 2  |
|  2 | user-b | chat-admin | 2  |
|  3 | user-c | moderator  | 3 |

One of the ways to paginate 1-to-n relationships is to use a subquery as I posted above on the issue, however I don't see how I can do that with this library.

**Comment by felixmosh** [comment]
This is not related to this lib.
This lib is only provides a cleaner api for pagination, calculate offset etc.

What you are looking for is [limit within a group](https://stackoverflow.com/questions/2129693/using-limit-within-group-by-to-get-n-results-per-group), this is a not trivial sql query to make.

I've 2 solution for you:
1. make 2 queries, one on users with pagination, then for them query the roles.
```javascript
const users = await db('users').paginate({ perPage: 20, currentPage: 2});
const roles = await db('roles').whereIn('user_id', users.map(user => user.id));

users.forEach(user => {
  user.roles = roles.filter(role => role.user_id===user.id);
})
```
2. take advantage of `Group_Concat` (I'm familiar with it from MySQL)
``` sql
Select users.*, Group_Concat(roles.role) From users Left Join roles On roles.uid=users.id Group By users.id, users.username
```
  [Working example](https://www.db-fiddle.com/f/tPSdezbXPuZmFxix8Qeakx/0).

  This kind of query will allow you to use `paginate` on it.

**Comment by JCMais** [comment]
Thanks, you gave me a general idea on what to do, as I'm using Postgres I ended up using `array_agg` and `json_agg` aggregation functions, so all related records are stored in a single column and they do not mess with OFFSET / LIMIT.
