### ISSUE TITLE
`.paginate` is not a function in KnexJS 3+

### ISSUE THREAD

**Issue by julzllanillo** [felixmosh/knex-paginate#48]
# Summary
Upgraded knexjs to `^3.0.0`, functions that uses `.paginate()` now returns this error:
```
this.transaction.select(...).from(...).leftJoin(...).leftJoin(...).leftJoin(...).leftJoin(...).leftJoin(...).leftJoin(...).leftJoin(...).where(...).groupBy(...).modify(...).orderByRaw(...).paginate is not a function
```

## Additional Notes
- No changes were done except to upgrade knexjs

**Comment by felixmosh** [comment]
Hi, thank you for reporting this issue, I'll check it asap.

**Comment by julzllanillo** [comment]
Hmmmm, I already tried using `.extend()` before anything else and it may be because of I'm using the library `backstage` from which I acquire the database. There may be something wrong in how it instantiate the knexjs with its current version. I'll close this issue since it is not connected with the library. Thanks for the swift response!
