### ISSUE TITLE
Getting result as array, not object

### ISSUE THREAD

**Issue by buianhthang** [felixmosh/knex-paginate#5]
Hi,

I'm using this package for my project but getting the result as an array. Could you have a look

this is not working, even I print the query, it's correct
```javascript
const { attachPaginate } = require('knex-paginate');
attachPaginate();

async function(query: any, options: any) {
    query.paginate({ perPage: options.limit || 50, currentPage: 1, isLengthAware: true });

    const result = await query

    // result is an array
    return {
        total: result.pagination.total,
        data: result.data,
    };
}
```

this is working well
```js
async function(query: any, options: any) {
    // FIXME: need to calculate current page from offset inside options
    const paging = query.paginate({ perPage: options.limit || 50, currentPage: 1, isLengthAware: true });

    const result = await paging

    return {
        total: result.pagination.total,
        data: result.data,
    };
}
```

npm package version:
knex: 0.21.0
knex-paginate: 1.2.0

**Comment by felixmosh** [comment]
It is intended, paginate is not a native sql method therefore it is not returning the same query but a new one (think about this, it runs under the hood 2 separate query, one for the count and other for the results).

You can a write it like this

´´´javascript 

async function(query: any, options: any) {
    // FIXME: need to calculate current page from offset inside options
    const result = await query.paginate({ perPage: options.limit || 50, currentPage: 1, isLengthAware: true });
    return {
        total: result.pagination.total,
        data: result.data,
    };
}

´´´

**Comment by buianhthang** [comment]
yeah, thank you for your explanation and suggestion. that's fine to me. I just found out the solution after the issue created.

**Comment by buianhthang** [comment]
@felixmosh is it possible to support `offset`? `offset` and `currentPage`, one of them is allowed at the same time

**Comment by felixmosh** [comment]
The whole idea of this lib is not to worry about offset (which is an implementation detail). 
I don't think that offset is a good addition.

Do you have a valid use case for the need for offset usage?
