### ISSUE TITLE
Request: get all rows parameter

### ISSUE THREAD

**Issue by andrescellini** [felixmosh/knex-paginate#57]
in some cases i have to get all rows, for example to export to a file.

it will be usefull having some value of "perPage" like -1 to skip the total and last page querys ( or calcuate from data even, and not counting in db )

thks

**Comment by felixmosh** [comment]
You can apply it conditionally, with something like
```js
const baseQuery = knex('tableName').where('size','>', 100)
const rows = await (showAll ? baseQuery : baseQuery.paginate( .... )
```
Is this not enough?

**Comment by andrescellini** [comment]
it is a way, but change the contract of the response, it will be usefull having that, thats all.

thks anyway

**Comment by felixmosh** [comment]
Will you make a PR that adds a disabled flag, which disables the pagination?

**Comment by felixmosh** [comment]
Since there were several changes, I decided to make a PR

**Comment by felixmosh** [comment]
Thank you for the feature request 🙏🏽

**Comment by andrescellini** [comment]
cool!
