### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by andrescellini** [felixmosh/knex-paginate#59]
ey, here is a suggestion to imporove performance.

since leftjoin or outterapply ( in case the where clausule not reference any of those tables ) dont change the count, you can avoid doing that in the "shouldFetchTotals" phase.

i am sure there are cases when its not so easy to detect if the left join is affecting or not the count , but the improvment is big in complex querys, maybe with a experimental flag to try it first worth the shot. 

idk, just an idea.

**Comment by andrescellini** [comment]
also order, maybe can avoid order in count right?

**Comment by felixmosh** [comment]
Hi, thanks.

But this is not true, you can join other table and add a where clause based on the joined table columns.

**Comment by felixmosh** [comment]
We are clearing the offset and the order...
