### ISSUE TITLE
Sorting support

### ISSUE THREAD

**Issue by kenhuang** [felixmosh/knex-paginate#8]
Thanks for the library, comparing to other stacks notice they do support for sorting.

https://github.com/jhipster/jhipster-sample-app-nodejs/blob/master/server/src/domain/base/pagination.entity.ts#L29
https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Pageable.html

**Comment by felixmosh** [comment]
Thank you for opening this issue 🙏🏼

You can sort the data, just put the `orderBy` statement **before** `paginate`, since `paginate` is forking the original query and execute 2 queries in order to determine the total count.

So for example if your original query looks like:
```javascript
knex('users').columns('id', 'name').paginate({perPage: 10, currentPage: 1});
```
Convert it to:
```javascript
knex('users').columns('id', 'name').sortBy('id').paginate({perPage: 10, currentPage: 1});
```

**Comment by kenhuang** [comment]
👍 thanks!
